#!/usr/bin/env bash

bin/download 2.4.7 community
bin/start --no-dev
bin/composer install
bin/clinotty rm -rf generated/code/* generated/metadata/*
bin/setup magento.test
bin/composer require markshust/magento2-module-disabletwofactorauth
bin/magento module:enable MarkShust_DisableTwoFactorAuth
bin/magento module:disable Magento_AdminAdobeImsTwoFactorAuth Magento_TwoFactorAuth
bin/clinotty bin/magento cache:flush
bin/magento setup:upgrade